version: "3.12"

services:
  kekikstreamapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kekikstreamapi
    restart: unless-stopped
    ports:
      - "3310:3310"
    environment:
      DEBIAN_FRONTEND: noninteractive
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
      PYTHONIOENCODING: "UTF-8"
      LANG: "tr_TR.UTF-8"
      LC_ALL: "tr_TR.UTF-8"
      LANGUAGE: "tr_TR:tr"
      TZ: "Europe/Istanbul"
